var gulp = require('gulp');
var del = require('del');
var merge = require('merge-stream');
var sass = require('gulp-sass');
var header = require('gulp-header');
var importOnce = require('node-sass-import-once');
var concat = require('gulp-concat');
var path = require('path');
var replace = require('gulp-replace');

gulp.task('clean', function() {
  return del([
    'web/themes/custom/relaunch2018/css',
    'web/themes/custom/relaunch2018/lib/bootstrap',
    'web/themes/custom/relaunch2018/lib/hammerjs',
    'web/themes/custom/relaunch2018/lib/jquery.easing',
    'web/themes/custom/relaunch2018/lib/popper.js',
    'web/themes/custom/relaunch2018/lib/fonts/barlow',
    'web/themes/custom/seven_subtheme/css',
    'web/modules/custom/form_alterations/css'
  ]);
});

gulp.task('scss', function() {
  var headerNote = ['@charset "UTF-8";',
    '/**',
    ' * !!! DO NOT EDIT THIS FILE !!!',
    ' * For changing styles, edit the corresponding SCSS file(s) and compile',
    ' * those to CSS files.',
    ' */',
    ''].join('\n');
  var root = 'web/themes/custom/relaunch2018/';
  var sassOptions = {
    importer: importOnce,
    includePaths: [
      path.resolve(__dirname + '/web/libraries/bootstrap/scss'),
      path.resolve(__dirname + '/web/themes/custom/relaunch2018/scss/_includes')
    ]
  };

  return merge(

    // Frontend theme CSS
    gulp.src([
      root + 'scss/*.scss',
      root + 'scss/nodes/*.scss',
      root + 'scss/paragraphs/*.scss',
      root + 'scss/views/*.scss'
    ])
    .pipe(concat('global.scss'))
    .pipe(sass(sassOptions))
    .pipe(replace(/@charset [^;]+;/g, ''))
    .pipe(header(headerNote))
    .pipe(gulp.dest(root + 'css')),

    // Standalone styles.css is supplied to backend CKEditor.
    gulp.src(root + 'scss/styles.scss')
    .pipe(sass(sassOptions))
    .pipe(replace(/@charset [^;]+;/g, ''))
    .pipe(header(headerNote))
    .pipe(gulp.dest(root + 'css')),

    // Admin theme CSS
    gulp.src('web/themes/custom/seven_subtheme/scss/*.scss')
    .pipe(concat('styles.scss'))
    .pipe(sass(sassOptions))
    .pipe(replace(/@charset [^;]+;/g, ''))
    .pipe(header(headerNote))
    .pipe(gulp.dest('web/themes/custom/seven_subtheme/css')),

    // Custom form CSS
    gulp.src('web/modules/custom/form_alterations/scss/*.scss')
    .pipe(sass(sassOptions))
    .pipe(replace(/@charset [^;]+;/g, ''))
    .pipe(header(headerNote))
    .pipe(gulp.dest('web/modules/custom/form_alterations/css'))
  );
});

gulp.task('default', gulp.series('clean', 'scss'), function() {});
