<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\user\Entity\User;

const USER_MANAGEMENT_DEFAULT_ROLE_ID = 'participant';
const USER_MANAGEMENT_SELECTABLE_ROLE_IDS = ['institution', 'participant'];

/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_management_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $currentUser = \Drupal::currentUser();
  $roles = $currentUser->getRoles();

  if (in_array('anonymous', $roles)) {
    // Hide region field on the visitor's registration form.
    $form['field_region']['#access'] = false;
  }
  else if (
    !$currentUser->hasPermission('administer_permissions')
    && in_array('event_manager', $roles)
  ) {
    // Limit event managers to only assign their respective region(s) to users
    // they create.

    $regionIds = _user_management_get_user_regions($currentUser);

    $form['field_region']['widget']['#default_value'] = [];

    foreach (array_keys($form['field_region']['widget']['#options']) as $termId) {
      if (in_array($termId, $regionIds)) {
        $form['field_region']['widget']['#default_value'][] = $termId;
      }
      else {
        $form['field_region']['widget'][$termId]['#disabled'] = true;
      }
    }
  }

  $role = \Drupal::request()->query->get('role');

  if (in_array($role, USER_MANAGEMENT_SELECTABLE_ROLE_IDS)) {
    $form['user_management__role'] = [
      '#type' => 'hidden',
      '#value' => $role,
    ];
  }

  $form['actions']['submit']['#submit'][] = '_user_management_submit';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function user_management_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id !== 'user_form') {
    return;
  }

  $currentUser = \Drupal::currentUser();
  $roles = $currentUser->getRoles();

  if (
    $currentUser->hasPermission('administer_permissions')
    || !in_array('event_manager', $roles)
  ) {
    return;
  }

  // Limit event managers to only change their respective region(s) on existing
  // users.

  $regionIds = _user_management_get_user_regions($currentUser);

  foreach (array_keys($form['field_region']['widget']['#options']) as $termId) {
    if (!in_array($termId, $regionIds)) {
      $form['field_region']['widget'][$termId]['#disabled'] = true;
    }
  }
}

/**
 * Custom submit handler for the user registration form.
 * If a role id was specified using a query parameter, the submit handler will
 * update the new user assigning the user that role, as long as that role is
 * allowed to be set automatically.
 *
 * @param $form
 * @param FormStateInterface $form_state
 */
function _user_management_submit($form, FormStateInterface &$form_state) {
  $roleId = USER_MANAGEMENT_DEFAULT_ROLE_ID;

  if ($form_state->hasValue('user_management__role')) {
    $roleId = $form_state->getValue('user_management__role');

    $roleId = in_array($roleId, USER_MANAGEMENT_SELECTABLE_ROLE_IDS)
      ? $roleId : USER_MANAGEMENT_DEFAULT_ROLE_ID;
  }

  $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($roleId);

  if ($role !== null) {
    $user = User::load($form_state->getValue('uid'));
    $user->addRole($role->id());
    $user->save();
  }
}

/**
 * @param AccountProxyInterface $user
 * @return array
 */
function _user_management_get_user_regions(AccountProxyInterface $user) {
  $user = User::load($user->id());
  return array_map(function($value) {
    return $value['target_id'];
  }, $user->get('field_region')->getValue());
}
