views.filter.views_entity_reference:
  type: views_filter
  mapping:
    views_entity_reference_target_bundles:
      type: sequence
      label: Entity reference selection ID
      sequence:
        - type: string
