<?php

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param array $variables
 */
function form_alterations_preprocess_file_upload_help(array &$variables) {
  // Remove unneeded explanations
  // - number of files:
  unset($variables['descriptions'][0]);
  // - maximum file size:
  unset($variables['descriptions'][1]);
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * @param array $element
 * @param FormStateInterface $form_state
 * @param array $context
 */
function form_alterations_field_widget_options_select_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  if (
    isset($context['form']['#entity_type'])
    && $context['form']['#entity_type'] === 'paragraph'
  ) {
    $element['#options']['_none'] = t('- Select -');

    if (in_array('field_attributed_image', $element['#field_parents'])) {
      // Supply info for functionality to hide attribution input field on public
      // domain licenses.
      /** @var \Drupal\taxonomy\TermStorage $storage */
      $storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');

      $topLevelTerms = $storage->loadTree('licenses', 0, 1);

      $publicDomainGroups = array_filter($topLevelTerms, function($term) {
        return in_array(
          strtolower($term->name),
          ['public domain', 'gemeinfrei']
        );
      });

      $publicDomainTermIds = [];

      foreach ($publicDomainGroups as $groupTerm) {
        foreach ($storage->loadTree('licenses', intval($groupTerm->tid), 1) as $term) {
          $publicDomainTermIds[] = $term->tid;
        }
      }

      $element['#attributes']['data-public-domain']
        = json_encode($publicDomainTermIds);
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param string $form_id
 */
function form_alterations_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_data_set_form', 'node_data_set_edit_form'])) {
    _form_alterations_data_set($form);
  }
  elseif (in_array($form_id, ['node_project_form', 'node_project_edit_form'])) {
    _form_alterations_project($form);

    foreach ($form['field_team_members']['widget'] as $key => &$attribute) {
      if (is_int($key)) {
        $attribute['subform']['field_links']['widget']['add_more']['#value']
          = t('Add another link');
      }
    }
  }

  if (in_array($form_id, [
    'node_project_form',
    'node_project_edit_form',
    'node_data_set_form',
    'node_data_set_edit_form'
  ])) {
    $select2Fields = [
      'field_datasets',
      'field_keywords',
    ];

    foreach ($select2Fields as $fieldName) {
      $form[$fieldName]['widget']['#select2']['theme'] = 'seven';
      $form[$fieldName]['widget']['#select2']['placeholder'] = '';
    }
  }
}

/**
 * @param array $form
 */
function _form_alterations_data_set(array &$form) {
  _form_alterations_common_changes($form, [
    'field_metadata_doc_links',
    'field_links_api',
    'field_links_media',
    'field_links_metadata',
  ]);

  $form['#attached']['library'][] = 'form_alterations/checkbox-description';
  $form['#attached']['library'][] = 'form_alterations/checkbox-hierarchy';
  $form['#attached']['library'][] = 'form_alterations/multistep';

  unset($form['field_media_filesize']['widget'][0]['subform']['field_unit']['widget']['#options']['_none']);
  unset($form['field_metadata_filesize']['widget'][0]['subform']['field_unit']['widget']['#options']['_none']);

  $form['langcode']['widget'][0]['value']['#title'] = t('Language of this data set description');

  $userRoles = \Drupal::currentUser()->getRoles();

  if (
    count(
      array_intersect($userRoles, ['administrator', 'event_team', 'office'])
    ) === 0 && isset($form['field_legacy'])
  ) {
    $form['field_legacy']['#access'] = FALSE;
  }

  if (
    count(array_intersect($userRoles, ['administrator', 'office'])) === 0
    && isset($form['field_description_unconstrained'])
  ) {
    $form['field_description_unconstrained']['#access'] = FALSE;
  }
}

/**
 * @param array $form
 */
function _form_alterations_project(array &$form) {
  _form_alterations_common_changes($form, [
    'field_links',
    'field_other_datasets',
    'field_links_team',
  ]);

  $form['langcode']['widget'][0]['value']['#title'] = t('Language of this project description');
}

/**
 * @param array $form
 * @param string[]
 */
function _form_alterations_common_changes(array &$form, $linkFieldNames) {
  $currentUser = \Drupal::currentUser();
  $currentRoles = $currentUser->getRoles();

  if (count(array_intersect(['administrator', 'event_team', 'office'], $currentRoles)) === 0) {
    // When content is published and #access is set to FALSE, #default_value is
    // 'published', although the user does not have the permission to publish
    // directly. So, with #access being FALSE, the user's limitation to only
    // create new drafts on top of published content is circumvented. Therefore,
    // #default_value needs to be set manually.
    $form['moderation_state']['widget'][0]['state']['#default_value'] = 'draft';
    $form['#attached']['library'][] = 'form_alterations/styles';
  }

  foreach ($linkFieldNames as $linkFieldName) {
    $form[$linkFieldName]['widget']['add_more']['#value'] = t('Add another link');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param string $form_id
 */
function form_alterations_form_user_form_alter(array &$form, FormStateInterface $form_state, $form_id) {

  /** @var \Drupal\user\ProfileForm $profileForm */
  $profileForm = $form_state->getFormObject();

  /** @var \Drupal\user\Entity\User $user */
  $user = $profileForm->getEntity();

  if (count(array_intersect(['institution'], $user->getRoles())) === 0) {
    // Hide institution-specific user profile form element, if that profile is
    // not a institution profile.
    $form['#attached']['library'][] = 'form_alterations/user-profile-not-institution';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param string $form_id
 */
function form_alterations_form_user_register_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Always hide institution-specific user profile form element when creating
  // a new user.
  $form['#attached']['library'][] = 'form_alterations/user-profile-not-institution';
}

/**
 * Implements hook_entity_form_display_alter().
 *
 * @param EntityFormDisplayInterface $form_display
 * @param array $context
 */
function form_alterations_entity_form_display_alter(EntityFormDisplayInterface &$form_display, array $context) {
  $currentUser = \Drupal::currentUser();
  $currentRoles = $currentUser->getRoles();

  // Unfortunately, $context does not contain info that would allow retrieving
  // the roles of the user whose profile form is being rendered.
  // Consequently, the form mode is altered according to the user VIEWING the
  // form keeping in mind that user managers shall always be able to access all
  // fields. However, fields that do not apply to a particular user role are
  // hidden using CSS per form_alterations_form_user_form_alter.
  if (
    count(array_intersect(['administrator', 'event_team', 'office', 'institution'], $currentRoles)) > 0
    && $context['entity_type'] && $context['bundle'] === 'user'
  ) {
    $storage = \Drupal::entityTypeManager()->getStorage('entity_form_display');
    $institutionFormMode = $storage->load('user.user.institution');
    if ($institutionFormMode !== null) {
      $form_display = $institutionFormMode;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function form_alterations_preprocess_input__checkbox(&$variables) {
  if (
    isset($variables['element']['#parents'][0])
    && $variables['element']['#parents'][0] === 'field_access_mode'
  ) {
    // Add term description on access mode taxonomy term reference field to
    // input element.
    $tid = $variables['element']['#return_value'];
    $term = Term::load($tid);
    $variables['attributes']['data-description'] = $term->get('description')->value;
  }
}

/**
 * Implements hook_views_query_alter().
 */
function form_alterations_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  $currentUser = \Drupal::currentUser();
  $currentRoles = $currentUser->getRoles();

  if (count(array_intersect(['administrator', 'office'], $currentRoles)) === 0) {
    if ($view->id() === 'licenses') {
      $query->where[1]['conditions'][] = [
        'field' => 'taxonomy_term__parent.parent_target_id',
        'value' => '',
        'operator' => '!=',
      ];
    }
  }
}
