/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Hammer, window) {
  $(function () {
    $('.carousel').each(function () {
      var $carousel = $(this);

      $(window).on('resize orientationchange', function () {
        return normalizeCarouselHeights($carousel);
      });

      $carousel.on('slide.bs.carousel', function (e) {
        var $nextItem = $carousel.find('.carousel-item').eq(e.to);
        var $content = $nextItem.children('article');
        setTimeout(function () {
          $content.css('top', $nextItem.height() / 2 - $content.height() / 2 + 'px');
        }, 0);
      });

      new Hammer(this).on('panleft', function () {
        return $carousel.carousel('next');
      });

      new Hammer(this).on('panright', function () {
        return $carousel.carousel('prev');
      });

      $carousel.find('.carousel-item').each(function () {
        $(this).find('img').attr('draggable', 'false');
      });

      normalizeCarouselHeights($carousel);
    });
  });

  function normalizeCarouselHeights($carousel) {
    var $items = $carousel.find('.carousel-item');
    var maxHeight = 0;

    $items.each(function () {
      $(this).css('min-height', '0');
    });

    $items.each(function () {
      var height = $(this).height();

      if (height > maxHeight) {
        maxHeight = height;
      }
    });

    $items.each(function () {
      $(this).css('minHeight', maxHeight + ' px');
    });
  }
})(jQuery, Hammer, window);