/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($) {
  $(function () {
    $('[data-color-scheme-hover]').hover(function (e) {
      return changeColor(e, true);
    }, function (e) {
      return changeColor(e, false);
    });
  });

  function changeColor(event, mouseOver) {
    var $container = $(event.target).closest('[data-color-scheme-hover]');
    var color = getColor($container, mouseOver);

    if (color) {
      $container.stop(true).animate({
        backgroundColor: '#' + color
      }, {
        duration: 'fast'
      });
    }
  }

  function getColor($container, mouseOver) {
    var colorScheme = $container.data('color-scheme-hover');

    if ($.isArray(colorScheme) && colorScheme.length === 2) {
      return colorScheme[mouseOver ? 1 : 0];
    }

    if (typeof colorScheme === 'string') {
      $container.data('color-scheme-hover', [$container.css('background-color'), colorScheme]);
      return colorScheme;
    }

    return null;
  }
})(jQuery);