/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, drupalSettings) {
  $(function () {
    var $tileContainer = $('.tiles');
    var isFrontPage = $tileContainer.closest('body').hasClass('path-frontpage');
    var originalTileSize = isFrontPage ? 214 : 280;
    var tileSize = Math.sqrt(originalTileSize * originalTileSize * 2);

    var even = { top: 39, left: -113 };

    var odd = {
      top: even.top - tileSize / 2,
      left: even.left + tileSize / 2
    };

    var frontSideTilesCount = isFrontPage ? 42 : 20;
    var backSideTileCount = 24;
    var maxLines = isFrontPage ? 8 : 6;
    var lineLength = isFrontPage ? 8 : 6;

    var html = [];
    var frontSideI = 0;
    var backSideI = void 0;
    var l = void 0;
    var t = void 0;

    for (var i = 0; i < maxLines; i++) {
      for (var j = 0; j < lineLength; j++) {
        if (j % 2 === 0) {
          t = even.top + j / 2 * tileSize;
          l = even.left + i * tileSize;
        } else {
          t = odd.top + Math.floor(j / 2) * tileSize;
          l = odd.left + i * tileSize;
        }

        t = Math.round(t * 10) / 10;
        l = Math.round(l * 10) / 10;

        frontSideI++;
        backSideI = Math.floor(Math.random() * backSideTileCount);

        html.push('<div class="header-tile" style="left:' + l + 'px;top:' + t + 'px;">\n          <div class="flipper">\n          <div class="front cdv-tile-' + frontSideI % frontSideTilesCount + '"' + (drupalSettings.relaunch2018 && drupalSettings.relaunch2018.tiledHeader ? ' style="background-image:url(' + drupalSettings.relaunch2018.tiledHeader + ')"' : '') + '></div>\n          <div class="back code-tile-' + backSideI + '"></div>\n          </div>\n          </div>');
      }
    }

    $tileContainer.html(html.join(''));

    $('.header-tile').on('mouseenter touchstart', function (e) {
      $(e.target).closest('.header-tile').addClass('hover');
    }).on('mouseleave touchend', function (e) {
      $(e.target).closest('.header-tile').removeClass('hover');
    });
  });
})(jQuery, drupalSettings);