/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($) {
  $(function () {
    var $primaryMenu = $('.region-primary-menu');

    considerAdminToolbarOffset($primaryMenu);
    initAnimations($primaryMenu);
  });

  function initAnimations($primaryMenu) {
    var $toggler = $('.navbar-toggler');
    var $menu = $('#mainMenu');
    var $menuContainer = $menu.closest('.navbar--menu');

    $primaryMenu.find('.dropdown-toggle').on('click', function (e) {
      return e.preventDefault();
    }).parent().on('show.bs.dropdown hide.bs.dropdown', function (e) {
      $(this).find('.dropdown-menu').stop(true)[e.type === 'show' ? 'slideDown' : 'slideUp']({
        duration: 'fast',
        easing: 'easeInOutCirc'
      });
    });

    $menu.on('show.bs.collapse hide.bs.collapse', function (e) {
      var show = e.type === 'show';

      $toggler.toggleClass('collapsed', !show).attr('aria-expanded', show);

      $menuContainer.toggleClass('show', show);

      updateMenuItemTransitionDelays($menu, !show);
    });

    updateMenuItemTransitionDelays($menu, false);
  }

  function updateMenuItemTransitionDelays($menu, isShown) {
    $menu.find('.menu > li').each(function (i) {
      $(this).css('transition-delay', (isShown ? 0 : i * 0.05) + 's');
    });
  }

  function considerAdminToolbarOffset($primaryMenu) {
    var $body = $('body');

    if ($body.hasClass('toolbar-horizontal') || $body.hasClass('toolbar-vertical')) {
      var $navbar = $primaryMenu.find('.navbar.fixed-top');
      setPositions($navbar);

      $(window).on('resize', function () {
        return setPositions($navbar);
      });
    }
  }

  function setPositions($elements) {
    $elements.each(function () {
      var isFixed = $(this).css('position') === 'fixed';
      var $this = $(this);

      $this.css('position', 'absolute');

      if (typeof $this.data('relaunch2018-menu-position-top') === 'undefined') {
        $this.data('relaunch2018-menu-position-top', $this.position().top);
      }

      $this.css('top', $this.data('relaunch2018-menu-position-top') + parseFloat($('body').css('paddingTop')));

      if (isFixed) {
        $this.css('position', 'fixed');
      }
    });
  }
})(jQuery);