/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($) {
  $(function () {
    $('.node--type-article.node--view-mode-teaser, .node--type-article.node--view-mode-frontpage').each(function () {
      var $paragraphs = $(this).find('.field--name-field-paragraphs').find('p');

      if (!$paragraphs.length) {
        return;
      }

      var $links = $(this).find('.node__links').remove();

      if (!$links.length) {
        $links = $(this).find('.field--name-title').parent('a').clone();

        if (!$links.length) {
          return;
        }

        $links = $('<div>').addClass('node__links').append($('<ul>').addClass('links inline').append($('<li class="node-readmore">').append($links.clone().text('…'))));
      }

      $paragraphs.last().append($links);
    });
  });
})(jQuery);