/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($) {
  $(function () {
    $('.view-faq').find('.views-field-title a').on('click', function (e) {
      var $a = $(e.target);
      var $li = $a.closest('li');
      var $content = $li.find('.item-content');

      $content.stop(true)[$content.is(':visible') ? 'slideUp' : 'slideDown']({
        easing: 'easeInOutCirc'
      }).promise().done(function () {
        return $li[$content.is(':visible') ? 'addClass' : 'removeClass']('active');
      });

      return false;
    });
  });
})(jQuery);