<?php

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * @param array $suggestions
 * @param array $variables
 */
function seven_subtheme_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'form_element__' . $variables['element']['#type'];

  if (isset($variables['element']['#id'])) {
    $suggestions[] = 'form_element__'
      . $variables['element']['#type'] . '__'
      . str_replace('-', '_', $variables['element']['#id']);
  }
}
