<?php

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 * Adds a pre-render callback which allows changing the block content before
 * rendering.
 *
 * @param array $build
 */
function article_header_block_view_block_content_alter(array &$build) {
  if ($build['#id'] === 'article_header' || $build['#id'] === 'articles_header') {
    $build['#pre_render'][] = '_article_header_block_pre_render';
  }
}

/**
 * Pre-render callback for block user_login_block.
 *
 * @param array $build
 * @return array
 */
function _article_header_block_pre_render(array $build) {
  $build['content']['rss_link'] = [
    '#markup' => '<div class="article--rss--subscribe d-none d-md-block">'
      .'<a href="' . DRUPAL_ROOT . '/rss.xml" class="icon-rss">'
      . t('Subscribe to RSS feed')
      . '</a></div>',
    '#weight' => 99,
  ];
  return $build;
}