<?php

use Drupal\Core\Entity\ContentEntityInterface;

const LANGUAGE_SWITCHER_LANGUAGES = [
  'Englisch' => 'En',
  'Französisch' => 'Fr',
  'Deutsch' => 'De',
];

/**
 * Implements hook_language_switch_links_alter().
 *
 * @param array $links
 */
function language_switcher_language_switch_links_alter(array &$links) {
  $entity = _language_switcher_get_page_entity();

  foreach ($links as $langCode => &$link) {
    if (in_array($link['title'], array_keys(LANGUAGE_SWITCHER_LANGUAGES))) {
      $link['title'] = LANGUAGE_SWITCHER_LANGUAGES[$link['title']];
    }

    if (
      _language_switcher_is_view_route()
      || _language_switcher_is_registration_route()
    ) {
      continue;
    }

    if (!$entity) {
      unset($link['url']);
      continue;
    }

    try {
      if (!$entity->getTranslation($langCode)->access('view')) {
        // Content is not accessible (e.g. not published)
        unset($link['url']);
      }
    }
    catch (\InvalidArgumentException $e) {
      // Content is not translated.
      unset($link['url']);
    }
  }
}

/**
 * @return bool
 */
function _language_switcher_is_view_route() {
  return strpos(\Drupal::routeMatch()->getRouteName(), 'view.') !== FALSE;
}

/**
 * @return bool
 */
function _language_switcher_is_registration_route() {
  return !!preg_match(
    '/^user\.(login|pass|register)$/',
    \Drupal::routeMatch()->getRouteName()
  );
}

/**
 * Retrieves the current page entity.
 *
 * @return Drupal\Core\Entity\ContentEntityInterface|FALSE
 */
function _language_switcher_get_page_entity() {
  $params = \Drupal::routeMatch()->getParameters()->all();
  $entity = reset($params);
  if ($entity instanceof ContentEntityInterface) {
    return $entity;
  }
  return FALSE;
}
