<?php

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_block_access().
 *
 * @param Block $block
 * @param string $operation
 * @param AccountInterface $account
 * @return AccessResultInterface
 */
function list_edit_block_access(Block $block, $operation, AccountInterface $account) {
  if ($block->id() === 'views_block__projects_block_1' && $operation === 'view') {
    // Only show block for the current user. (Showing the block on Project Team
    // user pages only is already specified in the block config.)
    $pageUser = \Drupal::routeMatch()->getParameter('user');
    return AccessResult::forbiddenIf(
      $pageUser === null || $pageUser->id() !== \Drupal::currentUser()->id()
    );
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_views_pre_render().
 *
 * @param ViewExecutable $view
 */
function list_edit_views_pre_render(ViewExecutable $view) {
  if ($view->id() === 'projects' && $view->current_display === 'block_1') {
    $url = \Drupal\Core\Url::fromRoute('node.add', ['node_type' => 'project']);

    $view->attachment_after[] = [
      '#type' => 'form',
      '#action' => $url->toString(),
      'submit' => [
        '#type' => 'submit',
        '#value' => t('Create new project description'),
      ],
    ];
  }
}
