/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($) {
  $(function () {
    $('body').on('change', function (e) {
      if (e.target.hasAttribute('data-public-domain')) {
        hideAttributionInputOnPublicDomain(e.target);
      }
    });

    hideAttributionInputOnPublicDomain();
  });

  function hideAttributionInputOnPublicDomain(select) {
    var isPageLoad = !select;
    var $select = select ? $(select) : $('select[data-public-domain]');

    $select.each(function () {
      var $this = $(this);
      var $selectWrapper = $this.closest('.form-wrapper');
      var $subForm = $selectWrapper.closest('.paragraphs-subform');
      var $author = $subForm.find('.field--name-field-author');
      var licenses = $this.data('public-domain');

      if (!$author.length) {
        return;
      }

      var isPublicDomain = $.inArray($this.val(), licenses) !== -1;
      var animate = false;

      if (isPublicDomain && ($author.is(':visible') || $author.is(':animated'))) {
        if (isPageLoad) {
          animate = 'hide';
        } else {
          animate = $selectWrapper.css('display') === 'inline-block' ? 'fadeOut' : 'slideUp';
        }
      } else if (!isPublicDomain && (!$author.is(':visible') || $author.is(':animated'))) {
        animate = $selectWrapper.css('display') === 'inline-block' ? 'fadeIn' : 'slideDown';
      }

      if (animate) {
        $author.stop(true)[animate]().promise().done(function () {
          if (!$author.is(':visible')) {
            $author.find('input').val('');
          }
        });
      }
    });
  }
})(jQuery);