/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($) {
  $(function () {
    $('.block-block-figures').each(function () {
      $(this).find('[data-count]').each(function () {
        $(this).text('0');
      });

      $(this).find('.block-figures--item').eq(0).waypoint({
        handler: function handler() {
          var $counters = $(this.element).closest('.block-block-figures').find('[data-count]');
          count($counters.eq(0), $counters);
          this.destroy();
        },

        offset: 'bottom-in-view'
      });
    });
  });

  function count($counter, $counters) {
    $counter.countUp({
      last: $counter.data('count'),
      complete: function complete() {
        $counters.each(function (i) {
          if (this === $counter.get(0) && $counters.get(i + 1)) {
            count($counters.eq(i + 1), $counters);
          }
        });
      }
    });
  }
})(jQuery);