<?php

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param array $variables
 */
function login_preprocess_block__login_actions(array &$variables) {
  // Hide link to Login page from local tasks menu on Login page:
  $variables['content']['#primary']['user.login']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 */
function login_form_user_login_form_alter(array &$form) {
  $form['#attributes']['class'][] = 'container';

  $form['name']['#title_display'] = 'invisible';
  $form['pass']['#title_display'] = 'invisible';

  $form['name']['#placeholder'] = '{' . t('Username') . '}';
  $form['pass']['#placeholder'] = '{' . t('Password') . '}';

  unset($form['name']['#description']);
  unset($form['pass']['#description']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 */
function login_form_user_pass_alter(array &$form) {
  $form['name']['#title_display'] = 'invisible';
  $form['name']['#placeholder'] = '{' . t('Username or email address') . '}';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param array $form
 */
function login_form_user_register_form_alter(array &$form) {
  if (\Drupal::currentUser()->isAuthenticated()) {
    // Do not apply changes to backend's user registration form.
    return;
  }

  $form['account']['name']['#title_display'] = 'invisible';
  $form['account']['mail']['#title_display'] = 'invisible';

  $form['account']['name']['#placeholder'] = '{' . t('Username') . '}';
  $form['account']['mail']['#placeholder'] = '{' . t('Email address') . '}';
}
